/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_wtz_learntosing_utils_NativeMethod */

#ifndef _Included_com_example_wtz_learntosing_utils_NativeMethod
#define _Included_com_example_wtz_learntosing_utils_NativeMethod
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_wtz_learntosing_utils_NativeMethod
 * Method:    displayHelloWorld
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_wtz_learntosing_utils_NativeMethod_displayHelloWorld
  (JNIEnv *, jobject);

/*
 * Class:     com_example_wtz_learntosing_utils_NativeMethod
 * Method:    inputData
 * Signature: ([I)I
 */
JNIEXPORT jint JNICALL Java_com_example_wtz_learntosing_utils_NativeMethod_inputData
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     com_example_wtz_learntosing_utils_NativeMethod
 * Method:    process
 * Signature: (I[D[II[DII)[I
 */
JNIEXPORT jintArray JNICALL Java_com_example_wtz_learntosing_utils_NativeMethod_process
  (JNIEnv *, jobject, jint, jdoubleArray, jintArray, jint, jdoubleArray, jint, jintArray);

#ifdef __cplusplus
}
#endif
#endif
