#ifndef CONFIG
#define CONFIG

#define WINDOWSIZE 2048
#define PI 3.141592654
#define MAXINTERESTOSCILATIONPIXEL 20
#define SPECTRUMPOWERTHREDHOLD 75
#define SPECTRUMPOWERTHREDHOLDDOUBLE 150
#define POWERDIV 64
#define FREEFLOATINGRANGE 0.7
#define FREEFLOATINGRANGEDIV 0.1
#define VALIDINTERESTINGRANGE 0.2
#define AXESDIFFERENCEWEIGHT 0.25
#define INTERESTSTARTTHREDHOLD 1000
#define INTERESTENDTHREDHOLD 1000
#define ONSETTHREADHOLD 880

#define ONSETENDLARGERTHREDHOLD 0.12
#define ONSETENDSMALLTHREDHOLD 0.08
#define DIFFONSETENDLARGER 0.02
#define DIFFONSETENDSMALL 0.01

#define VALIDSCORERANGE 0.05


#endif // CONFIG

